name: Test Build

on:
  push:
    branches-ignore:
      - main  # Don't run on main since publish workflow handles it
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test Build Python 🐍 distributions 📦
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pip install -r test-requirements.txt
        python -m unittest discover -s tests
    - name: Install pypa/build
      run: python -m pip install build twine
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/
    - name: Check distribution
      run: twine check dist/*
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/